name: Build Susta Windows
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4 # Passage en v4
    
    - name: Set up Python
      uses: actions/setup-python@v5 # Passage en v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install PyQt6 PyQt6-WebEngine pyinstaller Pillow
        
    - name: Build EXE
      run: |
        python -m PyInstaller --noconsole --onefile --name "Susta_Win" susta.py
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4 # La version v4 qui corrige ton erreur
      with:
        name: Susta-Windows-Exe
        path: dist/Susta_Win.exe
